services:
  db:
    image: postgres:16
    container_name: lb-timesheet-db
    environment:
      POSTGRES_USER: app
      POSTGRES_PASSWORD: app
      POSTGRES_DB: lb_timesheet
    ports:
      - "5544:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
