#!/bin/sh
# first-migration.sh — create, verify and PROVE the initial migration.
#
# What it does, in order:
#   1. prisma validate + generate (fails fast if the schema is broken)
#   2. Generates the init migration SQL from the schema (migrate diff)
#   3. Appends prisma/invariants.sql (the one-open-shift partial unique index)
#   4. Creates a CLEAN database (lb_timesheet_migrate_test) in the docker Postgres
#   5. Runs `prisma migrate deploy` against it — the real production code path
#   6. Proves from pg_indexes that the partial unique index physically exists
#   7. Runs the database integrity tests against the freshly migrated database
#   8. Runs the full authoritative gate (npm run check) from the repo root
#
# It does NOT touch the existing dev database (lb_timesheet) and does NOT commit.
set -e

API="$(cd "$(dirname "$0")/.." && pwd)"
ROOT="$(cd "$API/.." && pwd)"
cd "$API"

echo ""
echo "── 1. validate + generate ─────────────────────────────────────────────"
npx prisma validate
npx prisma generate

echo ""
echo "── 2. generate init migration SQL ─────────────────────────────────────"
EXISTING="$(ls -d prisma/migrations/*_init 2>/dev/null | head -1 || true)"
if [ -n "$EXISTING" ]; then
  MIG="$EXISTING"
  echo "   reusing existing $MIG (delete it to regenerate from scratch)"
  SKIP_APPEND=1
else
  NAME="$(date +%Y%m%d%H%M%S)_init"
  MIG="prisma/migrations/$NAME"
  mkdir -p "$MIG"
  # Prisma 7.10 renamed the flag; try current name first, fall back once.
  # The CLI prints decorative log lines ("◇ injected env…") to STDOUT, which a
  # plain redirect captures into the SQL — filter to lines that are actual SQL.
  strip_noise() { grep -vE '^\s*(◇|Loaded Prisma config|Prisma schema loaded)' ; }
  if npx prisma migrate diff --from-empty --to-schema prisma/schema.prisma --script 2>/dev/null | strip_noise > "$MIG/migration.sql" \
     && grep -q 'CREATE TABLE' "$MIG/migration.sql"; then
    echo "   migrate diff OK (--to-schema)"
  else
    npx prisma migrate diff --from-empty --to-schema-datamodel prisma/schema.prisma --script | strip_noise > "$MIG/migration.sql"
    echo "   migrate diff OK (--to-schema-datamodel)"
  fi
  SKIP_APPEND=0
fi

cat > prisma/migrations/migration_lock.toml <<'LOCK'
# Please do not edit this file manually
# It should be added in your version-control system (e.g., Git)
provider = "postgresql"
LOCK

echo ""
echo "── 3. append invariants.sql ───────────────────────────────────────────"
if grep -q 'Shift_one_open_per_user' "$MIG/migration.sql"; then
  echo "   already appended — skipping"
else
  {
    echo ""
    echo "-- ── Appended from prisma/invariants.sql (Prisma cannot express these) ──"
    cat prisma/invariants.sql
  } >> "$MIG/migration.sql"
fi
echo "   appended. Migration: $MIG/migration.sql ($(wc -l < "$MIG/migration.sql") lines)"

echo ""
echo "── 4. verify the SQL contains every required construct ────────────────"
check() {
  if grep -qE "$2" "$MIG/migration.sql"; then
    echo "   ✓ $1"
  else
    echo "   ✗ MISSING: $1"
    FAILED=1
  fi
}
FAILED=0
check "ShiftStatus enum"                        'CREATE TYPE "ShiftStatus"'
check "Company table"                           'CREATE TABLE "Company"'
check "User table"                              'CREATE TABLE "User"'
check "CompanyMembership table"                 'CREATE TABLE "CompanyMembership"'
check "Shift table"                             'CREATE TABLE "Shift"'
check "ShiftSegment table"                      'CREATE TABLE "ShiftSegment"'
check "ShiftSubmitJob table"                    'CREATE TABLE "ShiftSubmitJob"'
check "membership 3-column unique"              'CompanyMembership_id_companyId_userId_key'
check "Shift→membership composite FK"           'FOREIGN KEY \("membershipId", "companyId", "userId"\)'
check "Shift (id,companyId) unique"             'Shift_id_companyId_key'
check "ShiftSegment same-company FK"            '"ShiftSegment".*FOREIGN KEY \("shiftId", "companyId"\)|ADD CONSTRAINT "ShiftSegment_shiftId_companyId_fkey"'
check "ShiftSubmitJob same-company FK"          'ADD CONSTRAINT "ShiftSubmitJob_shiftId_companyId_fkey"'
check "one-open-shift partial unique index"     'Shift_one_open_per_user'
[ "$FAILED" -eq 0 ] || { echo "!! SQL verification failed — inspect $MIG/migration.sql"; exit 1; }

echo ""
echo "── 5. migrate deploy against a CLEAN database ─────────────────────────"
docker exec lb-timesheet-db psql -U app -d postgres -q \
  -c 'DROP DATABASE IF EXISTS lb_timesheet_migrate_test' \
  -c 'CREATE DATABASE lb_timesheet_migrate_test'
CLEAN_URL="postgresql://app:app@localhost:5544/lb_timesheet_migrate_test?schema=public"
DATABASE_URL="$CLEAN_URL" npx prisma migrate deploy

echo ""
echo "── 6. prove the partial index exists (pg metadata, not our own code) ──"
docker exec lb-timesheet-db psql -U app -d lb_timesheet_migrate_test -c \
  "SELECT indexname, indexdef FROM pg_indexes WHERE tablename = 'Shift' AND indexname = 'Shift_one_open_per_user';"
COUNT=$(docker exec lb-timesheet-db psql -U app -d lb_timesheet_migrate_test -t -A -c \
  "SELECT count(*) FROM pg_indexes WHERE indexname = 'Shift_one_open_per_user' AND indexdef LIKE '%WHERE%';")
if [ "$COUNT" = "1" ]; then
  echo "   ✓ partial unique index physically present"
else
  echo "   ✗ partial index missing or not partial"; exit 1
fi
echo "   applied migrations:"
docker exec lb-timesheet-db psql -U app -d lb_timesheet_migrate_test -t -c \
  "SELECT migration_name, finished_at IS NOT NULL AS finished FROM _prisma_migrations;"

echo ""
echo "── 7. database integrity tests against the migrated clean DB ──────────"
DATABASE_URL="$CLEAN_URL" npm run test:db

echo ""
echo "── 8. full authoritative gate ─────────────────────────────────────────"
cd "$ROOT"
npm run check

echo ""
echo "══ ALL STEPS PASSED ═══════════════════════════════════════════════════"
echo "Migration: api/$MIG"
echo "Nothing committed. The dev database (lb_timesheet) was not touched."
